services:
   db:
     image: mariadb:10.11
     container_name: pastefy-db
     volumes:
       - dbvol:/var/lib/mysql

     environment:
       MYSQL_ROOT_PASSWORD: pastefy
       MYSQL_DATABASE: pastefy
       MYSQL_USER: pastefy
       MYSQL_PASSWORD: pastefy
     networks:
      - base
    
   # adminer for basic GUI access to the DB to change user account type
   adminer:
    image: adminer
    restart: always
    ports:
      - "9998:8080"
    networks:
      - base
   
   pastefy:
     depends_on:
       - db
     image: interaapps/pastefy
     container_name: pastefy
     ports:
       - "9999:80"
       
     environment:
       HTTP_SERVER_PORT: 80
       HTTP_SERVER_CORS: "*"
       DATABASE_DRIVER: mysql
       DATABASE_NAME: pastefy
       DATABASE_USER: pastefy
       DATABASE_PASSWORD: pastefy
       DATABASE_HOST: db
       DATABASE_PORT: 3306
       PASTEFY_LOGIN_REQUIRED_CREATE: "true"
       PASTEFY_GRANT_ACCESS_REQUIRED: "true"
       # Set this to your domain
       SERVER_NAME: https://paste.domain.tld
       # There is INTERAAPPS, GOOGLE, GITHUB, DISCORD, TWITCH
       OAUTH2_GITHUB_CLIENT_ID: ""
       OAUTH2_GITHUB_CLIENT_SECRET: ""
       OAUTH2_DISCORD_CLIENT_ID: ""
       OAUTH2_DISCORD_CLIENT_SECRET: ""
     networks:
      - base

volumes:
  dbvol:

networks:
  base:
    external: true 
