services:
    portainer:
      image: portainer/portainer-ce:latest
      container_name: portainer
      restart: always
      privileged: true
      volumes:
        - ~/apps/portainer/data:/data:Z
        - /var/run/docker.sock:/var/run/docker.sock:Z
      ports:
        - "9443:9443"
      networks:
        - base

networks:
  base:
    external: true