services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ~/apps/kuma/data:/app/data
    ports:
      - 3001:3001
    restart: always
    networks:
        - base

networks:
  base:
    external: true
